## Using the Pillow library

In [2]:
# First import the necessary libraries:
# pillow (only import the most used module)
# and numpy (import whole library and rename it np)

from PIL import Image
import numpy as np

In [5]:
# Checking what files are in your working directory
# (maybe different command if Windows is your underlying OS)

!ls

 code1.pdf   DC.png			 photos
 code2.pdf   DN1.png			 photos.zip
 code3.pdf   face_recognition.ipynb	 small_spy.jpg
 code4.pdf   FindtheSpy.ipynb		'Week 4 - in class demo.ipynb'
 code5.pdf   groupphoto.jpg		 WithPillow2.ipynb
 dc1.png     JamesBond.ipynb		 WithPillow.ipynb
 dc2.jpeg   'Linear systems 3x3.ipynb'


In [3]:
# Create a string variable containing your filename
# (Mine was called DC.png)

filename = 'DC.png'

# Create a PIL Image object by opening an image file
# (Note if you wish to load as only grey scale use the second command)

spy_colour = Image.open(filename)
spy_grey = Image.open(filename).convert('L')

In [4]:
# Whenever you create an object check its type

type(spy_colour)

PIL.PngImagePlugin.PngImageFile

In [5]:
# Show (or view the image)

spy_colour.show()

In [6]:
# Resize the image to the width and height (in pixels) that you wish

small_spy_colour = spy_colour.resize((32,32))

In [7]:
# Show (or view the image)

small_spy_colour.show()

In [12]:
# Save the new image as jpg

small_spy_colour.save('small_spy.jpg')

# Save the new image as png

small_spy_colour.save('small_spy.png')

In [13]:
# Check the files were created

!ls

 code1.pdf   DC.png			 photos
 code2.pdf   DN1.png			 photos.zip
 code3.pdf   face_recognition.ipynb	 small_spy.jpg
 code4.pdf   FindtheSpy.ipynb		 small_spy.png
 code5.pdf   groupphoto.jpg		'Week 4 - in class demo.ipynb'
 dc1.png     JamesBond.ipynb		 WithPillow2.ipynb
 dc2.jpeg   'Linear systems 3x3.ipynb'	 WithPillow.ipynb


In [8]:
# Convert the images to numpy arrays

spy_numpy = np.array(small_spy_colour)
spy_numpy_colour = np.array(spy_colour)
spy_numpy_grey = np.array(spy_grey)

In [9]:
# Check the types of the new objects

print(type(spy_numpy_colour))
print(type(spy_numpy))
print(type(spy_numpy_grey))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
# Find the shape of the numpy arrays
# Note the grey scale is only two dimensional
# The colour image requires a third dimension
# to store three separate colour channels: red, green and blue.

print(spy_numpy_colour.shape)

print(spy_numpy_grey.shape)

(64, 64, 3)
(64, 64)


In [24]:
# Other way - convert a numpy array to an image

# Create a two dimensional and a three dimensional numpy array
# that are 64 by 64 filled with random integers between 0 and 255

greydata = np.random.randint(0,255,size=(64, 64), dtype=np.uint8) 
print(greydata.shape)

colourdata = np.random.randint(0,255,size=(64, 64, 3), dtype=np.uint8) 
print(colourdata.shape)

(64, 64)
(64, 64, 3)


In [30]:
# Put a red square in the middle of the colour array
colourdata[16:48, 16:48] = [255, 0, 0] # red square in middle
# Put a black square in the middle of the grey scale array
greydata[16:48, 16:48] = [0]

In [31]:
# Convert numpy arrays to Image objects

colour_with_redsquare = Image.fromarray(colourdata) 

grey_with_blacksquare = Image.fromarray(greydata) 

In [32]:
# View the images

colour_with_redsquare.show()
grey_with_blacksquare.show()

In [34]:
# Create two 64 by 64 numppy arrays

x = np.random.randint(0,255,size=(10, 10), dtype=np.uint8)
y = np.random.randint(0,255,size=(10, 10), dtype=np.uint8)
print(x)
print(y)

[[128 156 237 253 223   1 171  27 216 127]
 [ 51  28 190 183 199  87 182  87  87 135]
 [234  82 169 106 189 234 205  93   4 212]
 [ 88  41  89  84 250  39   5 189 200 144]
 [107 172  76 237  63  64 167 195 225 143]
 [240  28 121  22 116  36  69  32 210 117]
 [ 24  58 149 208 239 101  70 177 215 195]
 [153 188 171 244 172 195 159  10 112 172]
 [ 79 221  84  54  63  14  79 102  13  78]
 [245 214 205 212  97 116  76  37  88 229]]
[[149  40  52 107 154 111 190 111 192  33]
 [ 34  82  16 193  18 228  62 214 242  31]
 [ 82 209 228 191 182  53  76 237 168  42]
 [211 167  19 122 246 189 230  79 208  19]
 [ 62  67 226 222 169   3 126  85 250 199]
 [149  76  71 143  76 210 151 137  82 133]
 [110 217 204  26 203  87  68 168 148  81]
 [ 67 228  45 122 127 183 189 250 157 235]
 [ 97   7 117  41 180 102 102  62 244 199]
 [144   2 118  34 130 203 135 129 117   8]]


In [35]:
# Print the SSR between the two arrays
# If the SSR is zero then arrays are identical

print ( np.sum((x-y)**2))

10815
